title: PRIME
default_lang: en
author:
  name: 'Joe Bloggs'
  email: joe@test.com
taxonomies:
  - category
  - tag
metadata:
  description: 'PRIME - A Clean, Modern, Responsive Theme for GravCMS '
summary:
  enabled: true
  format: short
  size: 180
  delimiter: '==='
blog:
  route: /blog
